### PR TITLE
Support node v20

### PR DESCRIPTION
**Pull request by karlkeefer**
This seems to work fine on my development instance - maybe we can bump this with no other changes?

### CODE REVIEW

**Comment by karlkeefer** [comment]
Bump on this PR - with a merge I can close my fork 😉

**Comment by SalahAdDin** [comment]
@Sklico could you review this? please.

**Comment by Krislunde** [comment]
Would also like this. Using old node versions are a potential security risk. So... bump.

**Comment by SalahAdDin** [comment]
This plugin seems to be unmaintained.

**Comment by karlkeefer** [comment]
If @Sklico gives me access I'd be up for contributing.
e.g. I could also help with the other open PR: #10

**Comment by SalahAdDin** [comment]
@Sklico Man?

**Pull request closed without merging**
